import requests
import csv
import base64
import os
import time
import shutil
from io import StringIO
from datetime import datetime, timezone, timedelta

# --- CẤU HÌNH ---
VPN_API = "http://www.vpngate.net/api/iphone/"
ISP_API = "http://ip-api.com/json/{}"
SAVE_DIR = "ovpn_files"
README_FILE = "README.md"
CUSTOM_CIPHER = "data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305:AES-128-CBC"

def get_servers():
    print(f"[*] Đang tải danh sách server...")
    try:
        res = requests.get(VPN_API, timeout=20)
        # Lọc bỏ dòng comment * và dòng trống
        raw = [line for line in res.text.splitlines() if not line.startswith('*') and line.strip()]
        
        # Xử lý header
        if "HostName" not in raw[0]:
            header = "HostName,IP,Score,Ping,Speed,CountryLong,CountryShort,NumVpnSessions,Uptime,TotalUsers,TotalTraffic,LogType,Operator,Message,OpenVPN_ConfigData_Base64"
            raw.insert(0, header)
            
        return list(csv.DictReader(StringIO("\n".join(raw))))
    except Exception as e:
        print(f"[!] Lỗi tải VPN API: {e}")
        return []

def get_isp(ip):
    try:
        # Timeout ngắn để không treo tool quá lâu
        res = requests.get(ISP_API.format(ip), timeout=3).json()
        # Xóa khoảng trắng để hiển thị gọn (VD: SoftBank Corp -> SoftBankCorp)
        return res.get('isp', 'Unknown').replace(" ", "")
    except:
        return "Unknown"

def clean_ovpn_content(text):
    return "\n".join([line for line in text.splitlines() if line.strip()])

def save_ovpn(server):
    try:
        ip = server['IP']
        speed = int(server['Speed']) / 1000000
        
        # Lấy ISP Name
        isp = get_isp(ip)
        
        filename = f"JP_{isp}_{ip}_{speed:.1f}Mbps.ovpn"
        path = os.path.join(SAVE_DIR, filename)

        raw_b64 = server['OpenVPN_ConfigData_Base64']
        decoded_config = base64.b64decode(raw_b64).decode('utf-8')
        content_cleaned = clean_ovpn_content(decoded_config)
        
        final_data = f"# JP | {isp} | {ip} | {speed:.1f}Mbps\n{CUSTOM_CIPHER}\n{content_cleaned}"
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write(final_data)
        
        # Trả về dữ liệu đầy đủ để ghi vào Readme (Đã thêm 'isp')
        return {
            "filename": filename,
            "hostname": server.get('HostName', '-'),
            "ip": ip,
            "isp": isp,  # <--- Dữ liệu mới
            "ping": server.get('Ping', '-'),
            "speed": speed,
            "country": "Japan"
        }
    except:
        return None

def update_readme(success_list):
    # Lấy giờ Việt Nam (UTC+7)
    tz_vn = timezone(timedelta(hours=7))
    now = datetime.now(tz_vn).strftime("%Y-%m-%d %H:%M:%S")
    
    # Tạo Header bảng có thêm cột ISP
    md_content = f"""# VPN Gate List - Japan (JP)
**Last Updated:** {now} (GMT+7)
**Total Servers:** {len(success_list)}

| Hostname | IP Address | ISP | Ping | Speed | Country | Download Config |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
"""
    
    for item in success_list:
        # Link tải file
        relative_link = f"./{SAVE_DIR}/{item['filename']}"
        
        # Thêm cột ISP vào dòng dữ liệu
        row = f"| {item['hostname']} | {item['ip']} | **{item['isp']}** | {item['ping']} ms | {item['speed']:.2f} Mbps | {item['country']} | [Download]({relative_link}) |\n"
        md_content += row
    
    md_content += "\n\n*Auto-generated by GitHub Actions*"
    
    with open(README_FILE, 'w', encoding='utf-8') as f:
        f.write(md_content)
    print("[*] Đã cập nhật README.md")

def main():
    if os.path.exists(SAVE_DIR):
        shutil.rmtree(SAVE_DIR)
    os.makedirs(SAVE_DIR)
    
    servers = get_servers()
    
    # Lọc server Nhật (JP) và sắp xếp theo tốc độ
    jp_list = sorted([s for s in servers if s['CountryShort'] == 'JP'], 
                     key=lambda x: int(x['Speed']), reverse=True)
    
    print(f"[*] Tìm thấy {len(jp_list)} server JP. Bắt đầu xử lý...")

    success_items = []
    
    # Giới hạn 100 server tốt nhất để tránh timeout
    for s in jp_list[:100]: 
        result = save_ovpn(s)
        if result:
            success_items.append(result)
        time.sleep(1) # Delay nhẹ

    update_readme(success_items)
    print(f"[*] Hoàn tất! Đã lưu {len(success_items)} file.")

if __name__ == "__main__":
    main()
