name: Auto Update VPN Gate

on:
  schedule:
    - cron: '*/10 * * * *' # <--- SỬA DÒNG NÀY (Chạy mỗi 10 phút)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Scraper Script
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "VPN Auto Bot"
          git config --global user.email "bot@github.com"
          git add .
          # Thêm dòng này để tránh lỗi nếu không có gì thay đổi
          git diff-index --quiet HEAD || git commit -m "Update VPN List: $(date)"
          git push
